### ISSUE TITLE
Feature request: High bit-depth Support

### ISSUE THREAD

**Issue by TbtBI** [sekrit-twc/EdgeFixer#5] opened 2019-03-22 07:30 UTC
Hi.

Now with [Avisynth+](https://github.com/pinterf/AviSynthPlus/tree/MT) supporting high bit-depth, is it possible to add high bit-depth support for the Avisynth plugin?

**Comment by sekrit-twc** [comment] 2019-03-22 23:52
Is there a need for high-depth support? EdgeFixer should be the first filter in a workflow, so the image should still be 8-bit at this point. The filter does not produce results warranting higher precision.

**Comment by TbtBI** [comment] 2019-03-23 01:32
I mean for cases where the source usually is UHD BD (10-bit video), mainly YUV420.

Now the filter affects only luma plane. Is it possible to add chroma planes too? Sometimes there are desaturaed lines. An option to turn on/off chroma will be useful.


Now in Readme:
```
ContinuityFixer(clip clip, int "left", int "right", int "top", int "bottom", int "radius")
ReferenceFixer(clip clip, clip ref, int "left", int "right", int "top", int "bottom", int "radius")
```
but the order is left, top, right, bottom.

**Comment by sekrit-twc** [comment] 2019-03-23 01:45
README.md: fixed
Chroma: it's best to use std.ShufflePlanes or U/VToY, since you probably need different parameters for those planes

High depth, at least for 9-16-bit can be added to VapourSynth, but I do not know much about Avisynth+. I do not use that software, and I am not familiar with the API.

**Comment by sekrit-twc** [comment] 2019-03-23 02:40
I added 16-bit support to VapourSynth. AviSynth version is Patch Welcome.

**Comment by TbtBI** [comment] 2019-03-23 03:37
Thanks for the chroma suggestion.

**Comment by TbtBI** [comment] 2019-03-24 07:44
[Avisynth+ patch for high bit-depth support](https://pastebin.com/raw/Vjr8WpeN).

[The new avisynth.h](https://github.com/pinterf/AviSynthPlus/blob/MT/avs_core/include/avisynth.h).

**Comment by sekrit-twc** [comment] 2019-03-24 18:38
Is AviSynth+ compatible with AviSynth?

**Comment by sekrit-twc** [comment] 2019-03-24 19:17
Please try with the latest master.

**Comment by TbtBI** [comment] 2019-03-24 20:46
It works properly with both AviSynth 2.6 and Avisynth+ 8-bit, but Avisynth+ high bit-depth output is wrong.
[10-bit](http://imgbox.com/1L0d9P4W) vs [8-bit](http://imgbox.com/01pzO2q9)

Also now the 64-bit build doesn't have [Avisynth export](http://imgbox.com/GH1XGIEf).

Btw those AviSynth/Avisynth+ checks and using different avisynth headers aren't needed? Avisynth+ is compatible with AviSynth 2.6. The latest Avisynth+ headers and the original patch work properly with AviSynth 2.6 too.

**Comment by sekrit-twc** [comment] 2019-03-24 21:24
Why is it wrong? I do not have AviSynth+, so I can not debug.

AVS+ header can not be included in distribution because it states that it does not contain the GPL exception.

**Comment by TbtBI** [comment] 2019-03-24 23:40
[This change](https://pastebin.com/raw/pGF1M8WE) gives correct output, but [this one](https://pastebin.com/raw/CYwd4fVZ) gives the same wrong output. I had to force compiling with only Avisynth+ headers bacause AviSynth 2.6 doesn't have ComponentSize() and the compiler gives error if I change component_size(vi) to vi.ComponentSize().

I'm not aware of the licensing things. I saw some projects with recent Avisynth+ headers, that's why I thought including them shouldn't be a problem - [ffms2_cplugin](https://github.com/qyot27/ffms2_cplugin/tree/patches/src/avisynth_c), [HDRTools](https://github.com/jpsdr/HDRTools/tree/master/HDRTools), [RemoveDirt](https://github.com/pinterf/RemoveDirt/tree/master/RemoveDirt).

**Comment by sekrit-twc** [comment] 2019-03-25 02:03
Is it because is_avisynth_plus() returns false?

**Comment by sekrit-twc** [comment] 2019-03-25 02:18
I downloaded AvisynthPlus-r2772-MT-filesonly.7z and could not reproduce the issue.

    FFVideoSource("test.m2ts")
    ConvertTo16Bit()
    ContinuityFixer(left=1, right=1, top=1, bottom=1)
    ConvertTo8Bit()

**Comment by TbtBI** [comment] 2019-03-25 02:44
Just compiled again with "git clean -xfd" and "git reset --hard origin" before.
[The source](https://www.upload.ee/files/9740665/qkhrih.7z.html).
8-bit script:
```
FFVideoSource("qkhrih.mkv")
LoadPlugin(".\EdgeFixer\Release\EdgeFixer.dll")
ConvertBits(8)
ContinuityFixer(6,6,6,6,12)
```
[The result](http://imgbox.com/fvH5hWCn).
```
10-bit script:
FFVideoSource("qkhrih.mkv")
LoadPlugin(".\EdgeFixer\Release\EdgeFixer.dll")
#ConvertBits(8)
ContinuityFixer(6,6,6,6,12)
```
[The result](http://imgbox.com/jxzfMNwS).
I just loaded solution file in VS2017, changed SDK version and built it.  Should I do anything else?

**Comment by sekrit-twc** [comment] 2019-03-25 04:13
Are you sure avisynth.h is resolving to AVS+? I opened "qkhrih.mkv" on my side and do not see the issue. Please try the attached test build.

[EdgeFixer.zip](https://github.com/sekrit-twc/EdgeFixer/files/3001461/EdgeFixer.zip)

**Comment by TbtBI** [comment] 2019-03-25 05:56
Your file is working.

> EDIT2: Did you define AVISYNTH_PLUS before compiling?

No, I didn't. After adding "#define AVISYNTH_PLUS", everything is ok. I'm sorry wasting your time for something like this. I thought that AVISYNTH_PLUS is detected auto when submodule is initiated and updated.

> EDIT: I do not think EdgeFixer is the appropriate filter for this content. EdgeFixer fixes bright/dark lines, not blurry ones.

That was random picked video. It will be used for cases like this:
[Source](http://imgbox.com/4baoSwzI) vs [Only luma fixed](http://imgbox.com/y6XKgAXx) vs [Luma and chroma fixed](http://imgbox.com/Lj2VcJ1y)

Thanks for the implementation of high bit-depth support.

**Closed** 2019-03-25 15:56 UTC
